baseURL = 'https://wearephotosocial.com'
languageCode = 'en-gb'
defaultContentLanguage = "en-gb"
#title = 'Photo Social'
theme = 'lynx'

# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
   name = "ğŸ“¸ We Are Photo Social! ğŸ§‘ğŸ½â€ğŸ¦±ğŸ‘©ğŸ¼ğŸ‘©ğŸ¾â€ğŸ¦±ğŸ‘¨ğŸ¼â€ğŸ¦³"
  headline = "A London based, social community of creatives who connect through a love of photography!"
  # image = "img/author.jpg"  # path relative to static directory

  links = [
     { email = "mailto:wearephotosocial@gmail.com" },
     { instagram = "https://www.instagram.com/wearephotosocial/" },
     { link = { href = "https://calendar.google.com/calendar/embed?src=wearephotosocial%40gmail.com&ctz=Europe%2FLondon", text = "Events Calendar" } },
     { link = { href = "Photo-Social-Hosting-Guide-FINAL.pdf", text = "Photo Social Hosting Guide" } },
     { link = { href = "How-to-use-WhatsApp-Groups-for-Events.pdf", text = "How to use WhatsApp Groups for events" } },

    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
    # { bluesky = "https://bsky.app/profile/username" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/username" },
    # { youtube = "https://youtube.com/username" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
