baseURL = 'https://wearephotosocial.com'
languageCode = 'en-gb'
title = 'We Are Photo Social'
theme = 'lynx'

# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
   name = "ğŸ“¸ We Are Photo Social ğŸ§‘ğŸ½â€ğŸ¦±ğŸ‘©ğŸ¼ğŸ‘©ğŸ¾â€ğŸ¦±ğŸ‘¨ğŸ¼â€ğŸ¦³"
  headline = "A London based, social community of creatives who connect through a love of photography!"
  # image = "img/author.jpg"  # path relative to static directory

  links = [
     {email = "mailto:wearephotosocial@gmail.com" },
     { instagram = "https://www.instagram.com/wearephotosocial/" },
     { link = { href = "https://calendar.google.com/calendar/embed?src=wearephotosocial%40gmail.com&ctz=Europe%2FLondon", text = "Events Calendar" } },
     { link = { href = "Photo-Social-Hosting-Guide-FINAL.pdf", text = "Photo Social Hosting Guide" } },
     { link = { href = "How-to-use-WhatsApp-Groups-for-Events.pdf", text = "How to use WhatsApp Groups for events" } },


    # { discord = "https://discord.gg/invitecode" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" }, 
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { medium = "https://medium.com/username" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/username" },
    # { youtube = "https://youtube.com/username" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
